<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Persons [
	<!ELEMENT Persons (Person*)>
	<!ATTLIST Persons version CDATA #REQUIRED>
	<!ELEMENT Person (Name, Firstname, Birthdate, Maritalstatus)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Firstname (#PCDATA)>
	<!ELEMENT Birthdate (#PCDATA)>
	<!ELEMENT Maritalstatus (#PCDATA)>
]>
<Persons version="FS2018">
	<Person>
		<Name>Duck</Name>
		<Firstname>Donald</Firstname>
		<Birthdate>1920-04-13</Birthdate>
		<Maritalstatus>SINGLE</Maritalstatus>
	</Person>
	<Person>
		<Name>Luke</Name>
		<Firstname>Lucky</Firstname>
		<Birthdate>1946-11-14</Birthdate>
		<Maritalstatus>SINGLE</Maritalstatus>
	</Person>
	<Person>
		<Name>Dalton</Name>
		<Firstname>Ma</Firstname>
		<Birthdate>1958-01-01</Birthdate>
		<Maritalstatus>WIDOWED</Maritalstatus>
	</Person>
</Persons>